version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:${PORT}"
    volumes:
      - postgres_data:/src/db
  web:
    build:
      context: .
    command: sh -c "alembic upgrade head && cd app && uvicorn main:app --reload --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
volumes:
  postgres_data:
