version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
  fastapi:
    build:
      context: .
    command: sh -c "sleep 3 && alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
